### ISSUE TITLE
application localization

### ISSUE THREAD

**Issue by macr0nz** [macr0nz/Chess-club-manager#4]
Приложение будет на русском или на английском? Я про локализацию UI

**Comment by mcroitor** [comment]
приложение в принципе должно поддерживать локализацию, и переключать язык необходимо по нажатию соответствующего пункта меню.
вообще-то это вопрос проектировщика, который ничего не спрашивает о структуре, внешнем виде и желаемой функциональности приложения.
уже решили на чем будете реализовывать? остался C#?

**Comment by macr0nz** [comment]
писать буду на c#, а точнее на asp.net (mvc скорее всего) серверную часть и на angularJs или mvc фронт

**Comment by mcroitor** [comment]
в общем, и локализация нужна, и вообще, легко расширяемая, за счет плагинов, структура.
